### PR TITLE
Delete keystone test helpers

### PR DESCRIPTION
**Pull request by gibizer**
This is necessary to remove a dependency cycle between keystone-operator and lib-common.

PR merging order:
- [x] Do some adjustment to allow moving the KeystoneAPIFixture
      -  https://github.com/openstack-k8s-operators/lib-common/pull/340
- [x] Copy the helper code to keystone-operator
      -  https://github.com/openstack-k8s-operators/keystone-operator/pull/311
- [ ] Adapt all the service operators to use the helpers from keystone-operator instead of lib-common. Can be merged in parallel:
  - [x] https://github.com/openstack-k8s-operators/nova-operator/pull/539
  - [x] https://github.com/openstack-k8s-operators/keystone-operator/pull/312
  - [x] https://github.com/openstack-k8s-operators/placement-operator/pull/76
  - [x] https://github.com/openstack-k8s-operators/glance-operator/pull/320
  - [x] https://github.com/openstack-k8s-operators/neutron-operator/pull/213
  - [x] https://github.com/openstack-k8s-operators/manila-operator/pull/141
  - [x] https://github.com/openstack-k8s-operators/ironic-operator/pull/337
  - [x] https://github.com/openstack-k8s-operators/horizon-operator/pull/221
  - [x] https://github.com/openstack-k8s-operators/heat-operator/pull/245
- [ ] Merge this PR to delete the unused helper from lib-common and therefore remove the keystone dependency
- [ ] Update the envtest.md in the docs repo
      - https://github.com/openstack-k8s-operators/docs/pull/64

### CODE REVIEW

**Comment by gibizer** [comment]
I need to split this into two PRs. The first does the necessary adaptation on the code that remains in lib-common so that it can be merged and allow merging the keystone-operator PR. Then the actual removal needs to be in a second PR after all the other operators are adapted to the move.

**Comment by gibizer** [comment]
> I need to split this into two PRs. The first does the necessary adaptation on the code that remains in lib-common so that it can be merged and allow merging the keystone-operator PR. Then the actual removal needs to be in a second PR after all the other operators are adapted to the move.

Done

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
