### PR TITLE
Delete infra test helpers

### PR DESCRIPTION
**Pull request by gibizer**
This is necessary to remove a dependency cycle. The helpers are moved to infra-operator/apis module.

PR merging order:
- [x] Copy the helper code to infra-operator
      -  https://github.com/openstack-k8s-operators/infra-operator/pull/127
- [x] Adapt all the service operators to use the helpers from infra-operator instead of lib-common. Can be merged in parallel:
  - [x] https://github.com/openstack-k8s-operators/nova-operator/pull/551
  - [x] https://github.com/openstack-k8s-operators/keystone-operator/pull/317
  - [x] https://github.com/openstack-k8s-operators/neutron-operator/pull/220
  - [x] https://github.com/openstack-k8s-operators/manila-operator/pull/151
  - [x] https://github.com/openstack-k8s-operators/ironic-operator/pull/342
  - [x] https://github.com/openstack-k8s-operators/heat-operator/pull/251
  - [x] https://github.com/openstack-k8s-operators/horizon-operator/pull/227
- [ ] Merge this PR to delete the unused helper from lib-common and therefore remove the infra dependency
- [ ] Update the envtest.md in the docs repo
      - https://github.com/openstack-k8s-operators/docs/pull/64

### CODE REVIEW

**Review by fmount — APPROVED** [review]
/lgtm

**Comment by fmount** [comment]
keystone was the last one, we can unblock this patch now

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
