### PR TITLE
Add CodeQL workflow to find security vulnerabilities

### PR DESCRIPTION
**Pull request by fao89**
https://codeql.github.com/

### CODE REVIEW

**Comment by stuggi** [comment]
Is this something you want to propose we should enable on all operators?

**Comment by stuggi** [comment]
> Is this something you want to propose we should enable on all operators?

I mean I am fine with it, I just think we should do it everywhere not only on individual repos

**Comment by fao89** [comment]
> Is this something you want to propose we should enable on all operators?

I think we can use this repo as a test,
yesterday I saw the insights about this module
https://deps.dev/go/github.com%2Fopenstack-k8s-operators%2Flib-common%2Fmodules%2Fopenstack/v0.0.0-20230119120622-e0f68a14523a
and I became curious if CodeQL could catch these securities suggestions earlier for us

**Review by stuggi — APPROVED** [review]

**Pull request merged**
