### PR TITLE
Use mariadb-operator/api in go.mod

### PR DESCRIPTION
**Pull request by dprince**
This updates lib-common so that it requires only the
mariadb-operator/api module (vs. the entire operator)
thus avoiding circular dependencies across the projects

### CODE REVIEW

**Review by stuggi — APPROVED** [review]
/lgtm

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
before we merge this lets better check the discussion I started at https://coreos.slack.com/archives/CQXJFGMK6/p1657268098604339

**Review by stuggi — COMMENTED** [review]
I think this can now be closed as the change was done as part of the reorg

**Comment by stuggi** [comment]
https://github.com/openstack-k8s-operators/lib-common/blob/master/modules/database/go.mod#L7

**Pull request closed without merging**
