### PR TITLE
Return by pointer for consistency

### PR DESCRIPTION
**Pull request by bogdando**
Signed-off-by: Bogdan Dobrelya <bogdando@yahoo.com>

### CODE REVIEW

**Comment by bogdando** [comment]
@stuggi @gibizer PTAL

**Comment by bogdando** [comment]
Actually, we must reverse, see the testing
by pointer https://go.godbolt.org/z/jaccozvT6
smart https://go.godbolt.org/z/99Wjf8nqf <<< use THIS

**Comment by bogdando** [comment]
this one is good to go as is. I moved the return by pointer vs value discussion elsewhere :)

**Review by gibizer — APPROVED** [review]
I agree to change this to pointer to have consistency across the helpers.

**Pull request merged**
