### PR TITLE
Normalize module/crd path

### PR DESCRIPTION
**Pull request by SeanMooney**
This change modifes how we calculate the path for a module
to allow github usernames with any case to funciton.
the previous code only work for all lowercase usernames

the usernames in github are canonically cases senseitve even
though any case is accpeted in the url.

The path on disk used by go will however be lowercase.
This change makes our code have the same behvior.

### CODE REVIEW

**Review by mrkisaolamb — APPROVED** [review]
lgtm to me. For more context: https://github.com/golang/go/blob/c54bc3448390d4ae4495d6d2c03c9dd4111b08f1/src/cmd/go/internal/module/module.go#L386-L389

**Review by stuggi — APPROVED** [review]
lgtm, I'll wait merging it as @gibizer mentioned on slack to do some more testing

**Review by gibizer — CHANGES_REQUESTED** [review]
I tested it in openstack-operator locally by adding the following to the main go.mod file and it does not work. We need a bit more involved path normalization unfortunately:
```diff
+
+// Sean's lib-common f7a552f208e7 is the same as upstrem main
+// it reproduce the issue with make test:
+// msg: "unable to read CRD files: stat /home/gibi/go/pkg/mod/github.com/SeanMooney/lib-common/modules/test@v0.0.0-20231209173030-f7a552f208e7/openshift_crds/cert-manager/v1: no such file or directory",
+// replace github.com/openstack-k8s-operators/lib-common/modules/certmanager => github.com/SeanMooney/lib-common/modules/certmanager v0.0.0-20231209173030-f7a552f208e7
+
+// replace github.com/openstack-k8s-operators/lib-common/modules/common => github.com/SeanMooney/lib-common/modules/common v0.0.0-20231209173030-f7a552f208e7
+
+// replace github.com/openstack-k8s-operators/lib-common/modules/test => github.com/SeanMooney/lib-common/modules/test v0.0.0-20231209173030-f7a552f208e7
+
+// Sean's lib-common 86cb239b7521 is the path normalization fix
+// but it is still reproduces the issue
+// msg: "unable to read CRD files: stat /home/gibi/go/pkg/mod/github.com/seanmooney/lib-common/modules/test@v0.0.0-20231214171430-86cb239b7521/openshift_crds/cert-manager/v1: no such file or directory",
+replace github.com/openstack-k8s-operators/lib-common/modules/certmanager => github.com/SeanMooney/lib-common/modules/certmanager v0.0.0-20231214171430-86cb239b7521
+
+replace github.com/openstack-k8s-operators/lib-common/modules/common => github.com/SeanMooney/lib-common/modules/common v0.0.0-20231214171430-86cb239b7521
+
+replace github.com/openstack-k8s-operators/lib-common/modules/test => github.com/SeanMooney/lib-common/modules/test v0.0.0-20231214171430-86cb239b7521
```
Golang normalizes the path from SeanMooney to !sean!mooney:
```
❯ ll '/home/gibi/go/pkg/mod/github.com/!sean!mooney'
total 4.0K
drwxr-xr-x 3 gibi gibi 4.0K Dec 15 12:15 lib-common
```

**Comment by gibizer** [comment]
/hold
I need to test this locally...

**Comment by gibizer** [comment]
This is works now

```diff
// Sean's lib-common b26b257697a3 is combined fix from Sean + me
// The openstack-operator make test passes with it
//  2023-12-15T14:40:04.989+0100	DEBUG	controller-runtime.test-env	reading CRDs from path	{"path": "/home/gibi/go/pkg/mod/github.com/!sean!mooney/lib-common/modules/test@v0.0.0-20231215120433-b26b257697a3/openshift_crds/route/v1"}
replace github.com/openstack-k8s-operators/lib-common/modules/certmanager => github.com/SeanMooney/lib-common/modules/certmanager v0.0.0-20231215120433-b26b257697a3

replace github.com/openstack-k8s-operators/lib-common/modules/common => github.com/SeanMooney/lib-common/modules/common v0.0.0-20231215120433-b26b257697a3

replace github.com/openstack-k8s-operators/lib-common/modules/test => github.com/SeanMooney/lib-common/modules/test v0.0.0-20231215120433-b26b257697a3
```

**Review by gibizer — APPROVED** [review]

**Review by stuggi — APPROVED** [review]
/lgtm thanks a lot @gibizer @SeanMooney

**Pull request merged**
